spring:
  application:
    name: Mine4Cut-server

  datasource:
    # H2 데이터베이스
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver
    #username: sa
    #password:

    # PostgreSQL
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  #h2:
    #console:
      #enabled: true
      #path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true # 모든 SQL 쿼리를 로그에 출력
    Properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: testKey
  expiration: 86400000