on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [ opened, reopened, edited, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start Docker daemon (for Testcontainers)
        run: |
          sudo systemctl start docker

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Check Docker status
        run: |
          docker info || echo "Docker not available"
          ls -l /var/run/docker.sock
          whoami
      
      - name: Run tests with Gradle (verbose)
        run: ./gradlew clean test --info
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          TESTCONTAINERS_VERBOSE: true
          DOCKER_HOST: unix:///var/run/docker.sock
